# Compiler
CC=g++

# Compiler flags
CFLAGS=-Wall
	#  -Wall turns on most, but not all, compiler warnings


all: clean main.o
	$(CC) $(CFLAGS) -o master main.o

main.o:
	$(CC) $(CFLAGS) -c main.cpp

clean:
	rm -f master *.o