PREFIX=$(HOME)/rpi_tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-

# Compiler
CC=$(PREFIX)g++

# Compiler flags
CFLAGS=-Wall
	#  -Wall turns on most, but not all, compiler warnings


all: clean main.o
	$(CC) $(CFLAGS) -o master main.o

main.o:
	$(CC) $(CFLAGS) -c main.cpp

clean:
	rm -f master *.o